{
 "title": "ASSUME: Nodal view",
 "time": { "from": "2018-12-31T23:00:00.000Z", "to": "2019-01-08T23:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "simulation",
    "query": "SELECT simulation\nFROM market_meta"
   },
   {
    "name": "market",
    "query": "SELECT \n  market_id\nFROM market_meta\nwhere simulation='$simulation'\ngroup by market_id ;"
   }
  ]
 },
 "panels": [
  {
   "title": "Nodal Dashboard",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Nodal Analysing Board\n\nThis board can be used to visualize the Grid statistics and usage.\nAs well as the prices at different locations of the grid."
   }
  },
  {
   "title": "Grid Information",
   "type": "orchestracities-map-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime, coalesce(abs(flow),0)/(s_nom * s_max_pu) as \"usage\", l.line as name, bus0, bus1, ST_AsGeoJSON(ST_GeomFromEWKT(wkt_srid_4326)) as geometry, l.simulation\nFROM lines_geo l\nleft join grid_flows g on l.line = g.line and l.simulation = g.simulation\nWHERE\n  $__timeFilter(datetime) AND\nl.simulation = '$simulation'\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Grid Flows Nodal",
   "type": "timeseries",
   "description": "Overview of nodal results",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "rawSql": "select $__timeGroupAlias(datetime, $__interval), line, avg(flow) as flow from grid_flows where simulation = '$simulation'\nAND $__timeFilter(datetime)\nGROUP BY 1, line\nORDER BY 1;\n"
    }
   ]
  },
  { "title": "Market Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 14 },
   "options": {
    "content": "# Market-specific Data\n\nData specific for the market depending on the choice made at te top of the panel\n\n"
   }
  },
  {
   "title": "Market Summary $market",
   "type": "timeseries",
   "description": "Overview of market results for the chossen market",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(product_start,$__interval),\n  node as \"Node\",\n  avg(demand_volume) AS \"Demand volume\",\n  avg(supply_volume) AS \"Supply volume\",\n  avg(price) AS \"Price\"\nFROM market_meta\nWHERE (\"simulation\" LIKE '$simulation') AND \"market_id\" = '$market' AND $__timeFilter(product_start)\nGROUP BY 1, node\nORDER BY 1;\n"
    }
   ]
  },
  {
   "title": "Accepted Bid Prices",
   "type": "timeseries",
   "description": "Bid prices of accepted bids per unit in the chosen market",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "€/MW" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(start_time,$__interval),\n  avg(accepted_price::float) AS \" \",\n  case\n    when bid_type isnull then concat(unit_id, '_SB')\n    when bid_type != '' then concat(unit_id, '_', bid_type)\n  end AS \"bid_id\"\nFROM market_orders\nWHERE\n  $__timeFilter(start_time) AND\n  market_id = '$market' AND\n  simulation = '$simulation'\nGROUP BY 1, unit_id, bid_id, bid_type\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Accepted Bid Volume",
   "type": "timeseries",
   "description": "Accepted Volume  per unit in chosen market",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(start_time,$__interval),\n  avg(accepted_volume) AS \" \",\n  case\n    when bid_type isnull then concat(unit_id, '_SB')\n    when bid_type != '' then concat(unit_id, '_', bid_type)\n  end AS \"bid_id\"\nFROM market_orders\nWHERE\n  $__timeFilter(start_time) AND\n  market_id = '$market' AND\n  simulation = '$simulation'\nGROUP BY 1, unit_id, bid_id, bid_type\nORDER BY 1"
    }
   ]
  }
 ]
}